### ISSUE TITLE
Port to other browsers

### ISSUE THREAD

**Issue by ElDeveloper** [hoyois/mediacenter#5]
Would this be possible? Or are there technical limitations?

**Comment by ElDeveloper** [comment]
Just found the FAQ, sorry!

**Comment by hoyois** [comment]
No problem. In fact, there *are* technical limitations: Safari is the only browser now that supports the beforeload event (it was removed from Blink, and never made it to Firefox).

**Comment by ElDeveloper** [comment]
Thanks for the info. The main reason why I asked, is because lately
Safari is feeling slower and choppier.
